### ISSUE TITLE
"Genesis" Infra Deployments

### ISSUE THREAD

**Issue by timbeiko** [eth-clients/holesky#6]
One reason testnets are sticky is that "all the other apps are there", and existing testnets have more infrastructure support. In order to make the transition to Holli smoother, it would be nice if a core set of popular contracts could be deployed shortly after Genesis, and if a set of infra providers across all major categories committed to support the network ASAP after launch. 

Some examples I've heard of that led people to use Goerli: 

- DEXes, e.g. Uniswap, SushiSwap, etc. 
- Stablecoins, e.g. DAI, USDC, etc. 
- Oracles, e.g. Chainlink
-  L2s, e.g. Arbitrum, Optimism, etc. 
- MEV infra (relay/builders)
- Native wallet support in Rainbow, MetaMask, etc. 

Given the lead time we have here, it would be good to try and reach out to these folks ahead of time for deployment and solicit the dev community for other examples.

**Comment by 0xBeshoy** [comment]
totally on point, and recent events regarding goETH were mostly because of this, devs didn't want to deploy to an isolated network, also every major protocol/dapp out there is implicitly supporting goerli only, so why anyone choose something else?
i don't know how this could be done, an open letter to the community maybe?

**Comment by sambacha** [comment]
Manifold Finance (re: securerpc.com) is committed to providing such services on bare metal instances in at least 2 regions. 

We would like to see if client teams would be open to coordinating their CI/CD workflows such that new client releases can be pushed and tested on a subset of nodes that are operated by us (as an example) so that these sorts of testing efforts are mot duplicated as much and can potentially find  issues not typically surfaced by standard CI workflows.

**Comment by dapplion** [comment]
Would be nice if that can be automated in a way that's repeatable locally.

**Comment by protolambda** [comment]
In personal capacity I'm interested to support the testnet with validators + maybe some faucet automation, I applied to both of the other genesis threads for that.

With OP Labs we're also looking at when/how to transition our Optimism L2 testnet from Goerli to Holesky. Given the amount of users that depend on testnet-infra of the OP-Goerli deployment we're looking for a smooth transition. At the same time it also seems like a better idea to start with a fresh testnet state, to clean up some technical debt, and not create a complicated state migration. So we can't guarantee every L2 testnet user immediately moves over, but we're definitely interested to support an L2 deployment at L1 genesis (or shortly after genesis).
